# https://docs.travis-ci.com/user/multi-os/
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
matrix:
    include:
        # Ubuntu 14.04
        -   os: linux
            dist: trusty
            sudo: required
            python: 2.7
install:
-   sudo apt-key update
-   sudo apt-get -yq update
#-   sudo apt-get -yq purge postgr*
#-   sudo apt-get -yq purge virtualbox*
# The Oracle Java install routinely times out, and we're not using it, so uninstall it.
#-   sudo apt-get -yq purge oracle-java*
#-   sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade

# Fails.
#-   DEBIAN_FRONTEND=noninteractive sudo apt-get -f -o Dpkg::Options::="--force-overwrite" install --yes npm
#-   sudo npm install
-   sudo apt-get -yq install nodejs

# Install NPM from upstream.
-   git clone git://github.com/npm/npm.git
-   cd npm/scripts
-   chmod +x install.sh
-   sudo ./install.sh
-   cd ../..

-   sudo npm install -g eslint
# Necessary on some versions of Ubuntu 14, which has a malformed npm/nodejs package.
-   sudo bash -c "[ ! -f /usr/bin/node ] && ln -s /usr/bin/nodejs /usr/bin/node || true"

script:
-   set -e
-   cd $TRAVIS_BUILD_DIR
-   ./checkjs.sh
