#!/bin/bash -e

srcdir=$(dirname $(readlink -f "$0"))

post()
{
    glib-compile-schemas "$1"
}

for ((i = 1;i <= $#;i++)) ;do
    case "${!i}" in
	--post)
	    declare -f post
	    exit 0
	    ;;
	-p)
	    ((i++))
	    prefix="${!i}"
	    ;;
	--nopost)
	    nopost=1
	    ;;
    esac
done

mkdir -p "${prefix}/usr/share/gnome-shell/extensions"
cp -r "${srcdir}/system-monitor@paradoxxx.zero.gmail.com" "${prefix}/usr/share/gnome-shell/extensions/"
mkdir -p "${prefix}/usr/bin"
cp "${srcdir}/system-monitor-applet-config.py" "${prefix}/usr/bin/system-monitor-applet-config"
mkdir -p "${prefix}/usr/share/applications"
cp "${srcdir}/system-monitor-applet-config.desktop" "${prefix}/usr/share/applications/"
for dir in "${srcdir}/"po/* ;do
    [[ -d "$dir" ]] && {
	lang=$(basename "$dir")
	mkdir -p "${prefix}/usr/share/locale/LC_MESSAGES/${lang}"
	msgfmt "$dir/system-monitor-applet.po" -o "${prefix}/usr/share/locale/LC_MESSAGES/${lang}/system-monitor-applet.mo"
    }
done
mkdir -p "${prefix}/usr/share/glib-2.0/schemas"
cp org.gnome.shell.extensions.system-monitor.gschema.xml "${prefix}/usr/share/glib-2.0/schemas/"
[[ -z $nopost ]] && post "${prefix}/usr/share/glib-2.0/schemas"
