#!/bin/sh

export XDG_SESSION_TYPE=x11
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Prevent screen from locking after inactivity.
# There's no password set, so we won't be able to unlock it.
gsettings set org.gnome.desktop.screensaver lock-enabled false

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
vncconfig -nowin &
dbus-launch --exit-with-session gnome-session
